spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quickhome_zch_hwz_gjc?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: fz5662155


#    mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quickhome.domain
  configuration:
    map-underscore-to-camel-case: false