spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/quickhome_web?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: timjohnson
    password: 2546e135093a6ae1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
tencent:
  cos:
    SecretId: AKIDKUYghZQTSJ0cApNk6YvlSyIRNJA5ungb
    SecretKey: AKVcaKzeBZoEf4WrJabQLDDCA0d2JRSH
    bucketAddr: ap-chengdu
    bucketName: quickhome-1315319695
    rootSrc: https://quickhome-1315319695.cos.ap-chengdu.myqcloud.com

#    mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quickhome.domain
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-field: deleted_zch_hwz_gjc
      logic-delete-value: 1
      logic-not-delete-value: 0
jwt:
  key: "quickHome_jwt_key_melody"
rsa:
  public_key: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCD+SAG7mXRsT/H2CQPUAg+8tf/npR2A9Ob5S+/wbdsZa4IPZ9XmUs4jsL18/bxFXQEeQ0EvRfuaED7NFrXsIm9D611dD/P/PZkiB8zdfBHilsut1eUwO0pMQ98GHlWokR6Xe19oxLY2+q9cttZ4dsgh8oIJAd60qHPlxJKtqinVQIDAQAB"
  private_key: "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIP5IAbuZdGxP8fYJA9QCD7y1/+elHYD05vlL7/Bt2xlrgg9n1eZSziOwvXz9vEVdAR5DQS9F+5oQPs0Wtewib0PrXV0P8/89mSIHzN18EeKWy63V5TA7SkxD3wYeVaiRHpd7X2jEtjb6r1y21nh2yCHyggkB3rSoc+XEkq2qKdVAgMBAAECgYANMsvJbauoqD+e8qaOknw0oXBJK/iggdr2nxnipVK9CEE6qUEHj3jmn95vHxY9/52B+gI7jFa5nNsM1GxWYF0x8gb5lM4SLZsiXMh0SWzibpRwtkOcq6Gbox3r6zawZMH88D9eNxFAP4JVYzFlPOM6g2KoWbbk36JIe3gM+HT0CQJBAJcNaULTXc1Ewmym5OpDlX1A8kKlyl8TuXbOI1gg6HqMTPbkJYJhQYSvvkJqQS3nfwuOoe2CTsrHDHuSTIpbkP0CQQDfqjpZc+gqbaSmO53jXUF+0SBk3PPw3IV29HfYtDvAh/sp9NSFrl3El2dgiAvP8sF/x5nLfXHYzWPI5kKufIs5AkEAjq+RdhmZavR/wAjrBkuvI3E9Jy3a+3LzZ8GTa4UydcigTzv2HrHmJQOp8qzSQx2BShaC6YuFCFF8fiIVgUC7tQJAGKMUqFPXKA1JzLHWc3wLQd/hVJruGAMChJbrOKipyExyQy3f1xXc6FHRJlX2DyLrY5rl+v9Hch01t6R9heDcKQJAW28u5tzfqtM3b9cSuL34KKkUTOdc6i0xw1OPNaIxW7VQMIxhy+TTjViwp5I5kRD/FspligjyT11AIzYoPLjCkw=="
